### ISSUE TITLE
can't access swagger and graphQL api 

### ISSUE THREAD

**Issue by yarigpopov** [yahoo/covid-19-api#23]
I'm trying to open these two pages and get 404
https://covid19.knowledge.yahoo.com/api/graphiql/index.html
https://covid19.knowledge.yahoo.com/api/graphiql/index.html

Is it intended or something doesn't work properly?

**Comment by aklish** [comment]
It is intended.  The hosted API is intended to serve the dashboard.  Because there is no API token, we are not hosting the API for direct consumption.  In addition to the disabling the introspection pages, we also lock down the API shapes that are permitted to those the dashboard uses.

**Comment by yarigpopov** [comment]
I see. Thanks for clarification
