### ISSUE TITLE
Database invalid insert error on mvn clean install

### ISSUE THREAD

**Issue by benjamincpugh** [yahoo/covid-19-api#33]
Hi,

We are getting an "invalid insert" error whenever we run mvn clean install from the latest. We run our analysis several times a week, our last successful pull was on Thursday. Is there anything that has happened between now and then that could be the culprit?

Here is an excerpt of the database builder errors we get on running `mvn clean install` (there are many of this error repeated)

`19:55:37.774 [com.yahoo.covid19.database.DatabaseBuilder.main()] ERROR com.yahoo.covid19.database.DatabaseBuilder - Invalid insert: Places(id=York_County,_Maine, type=[CountyAdminArea], label=York County, Maine, wikiId=York_County,_Maine, longitude=-70.66154, latitude=43.43966, population=207641, parentIds=[Maine], rank=null, errorCode=DANGLING_FOREIGN_KEY)
19:55:37.774 [com.yahoo.covid19.database.DatabaseBuilder.main()] ERROR com.yahoo.covid19.database.DatabaseBuilder - Invalid insert: Places(id=York_County,_Nebraska, type=[CountyAdminArea], label=York County, Nebraska, wikiId=York_County,_Nebraska, longitude=-97.59715, latitude=40.8727, population=14598, parentIds=[Nebraska], rank=null, errorCode=DANGLING_FOREIGN_KEY)
19:55:37.775 [com.yahoo.covid19.database.DatabaseBuilder.main()] ERROR com.yahoo.covid19.database.DatabaseBuilder - Invalid insert: Places(id=York_County,_Pennsylvania, type=[CountyAdminArea], label=York County, Pennsylvania, wikiId=York_County,_Pennsylvania, longitude=-76.68781, latitude=39.97303, population=449058, parentIds=[Pennsylvania], rank=null, errorCode=DANGLING_FOREIGN_KEY)`

**Comment by Chandrasekar-Rajasekar** [comment]
There were some changes in the our dataset that have invalidated all the healthRecords which is fixed. Everything should work now.
